name: forknet
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python>=3.7
  - pytorch=1.5.0
  - cudatoolkit=11.0
  - torchvision=
  - tensorboard=
  - tqdm=
  - scipy=
  - nibabel=
  - matplotlib=
  - ray-all=
