name: forknet_env
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python>=3.7
  - pytorch
  - cudatoolkit=11.0
  - torchaudio
  - torchvision
  - tensorboard
  - tqdm
  - scipy
  - nibabel
  - matplotlib
