name: forknet
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python>=3.7
  - pip
  - pytorch=1.5.0
  - pandas=1.1.3
  - cudatoolkit=10.1
  - torchvision=0.2.1
  - tensorboard=2.3.0
  - tqdm=4.55.1
  - scipy=1.5.2
  - nibabel=3.2.1
  - matplotlib=3.3.2
  - kornia=0.3.0
  - scikit-learn=0.23.2
  - scikit-image=0.17.2
  - pip:
      - tabulate
      - ray
